//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.DatabaseUtilites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Severity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string ProjectID { get; set; }
    }
}
